package: github.com/leizongmin/example
version: 0.0.0
import:
- package: gopkg.in/yaml.v2
- package: github.com/Masterminds/vcs
  version: ^1.2.0
- package: github.com/codegangsta/cli
- package: github.com/Masterminds/semver
  version: ^1.0.0
