package: github.com/leizongmin/example
version: 0.0.0
author: ""
homepage: ""
import:
- package: gopkg.in/yaml.v2
  version: '*'
- package: github.com/Masterminds/vcs
  version: '*'
- package: github.com/codegangsta/cli
  version: '*'
- package: github.com/Masterminds/semver
  version: '*'
