package: github.com/leizongmin/gogo
version: 0.0.1
author: "Zongmin Lei <leizongmin@gmail.com>"
homepage: "http://ucdok.com"
import:
- package: gopkg.in/yaml.v2
  version: "*"
- package: github.com/mgutz/ansi
  version: '*'
